/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD (see esbuild.config.mjs)
If you want to view the source, see main.ts in this folder.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AIHarnessPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// types.ts
var VIEW_TYPE_CHAT = "ai-harness-chat";

// chat-view.ts
var import_obsidian = require("obsidian");
var ChatView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.controller = null;
    this.busy = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "AI Chat";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("ai-harness-chat");
    const header = containerEl.createDiv({ cls: "ai-harness-chat-header" });
    const title = header.createSpan({ cls: "ai-harness-chat-title" });
    title.createSpan({ text: "AI Chat" });
    title.createSpan({ text: `v${this.plugin.version}`, cls: "ai-harness-chat-version" });
    const actions = header.createSpan({ cls: "ai-harness-chat-actions" });
    const newBtn = actions.createEl("button", {
      text: "New",
      cls: "ai-harness-new-btn"
    });
    newBtn.addEventListener("click", () => this.newConversation());
    const closeBtn = actions.createEl("button", {
      text: "Close",
      cls: "ai-harness-new-btn ai-harness-close-btn"
    });
    closeBtn.addEventListener("click", () => this.plugin.closeChatView());
    this.messagesEl = containerEl.createDiv({ cls: "ai-harness-messages" });
    const statusRow = containerEl.createDiv({ cls: "ai-harness-status-row" });
    this.statusDot = statusRow.createSpan({ cls: "ai-harness-dot" });
    this.statusEl = statusRow.createSpan({ cls: "ai-harness-status-text" });
    const inputRow = containerEl.createDiv({ cls: "ai-harness-input-row" });
    this.input = inputRow.createEl("textarea", {
      cls: "ai-harness-input",
      placeholder: "Ask\u2026  (Enter to send, Shift+Enter for newline)"
    });
    this.sendBtn = inputRow.createEl("button", {
      text: "Send",
      cls: "ai-harness-send-btn"
    });
    this.sendBtn.addEventListener("click", () => this.send());
    this.input.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.send();
      }
    });
    this.renderHistory();
    this.checkConnection();
  }
  async onClose() {
    var _a;
    (_a = this.controller) == null ? void 0 : _a.abort();
    this.controller = null;
  }
  /** Render the persisted conversation history into the messages area. */
  renderHistory() {
    this.messagesEl.empty();
    const history = this.plugin.history;
    if (history.length === 0) {
      this.messagesEl.createDiv({
        cls: "ai-harness-empty",
        text: "No messages yet. Ask something below."
      });
      return;
    }
    for (const msg of history) {
      if (msg.role === "user" || msg.role === "assistant") {
        this.appendMessage(msg.role, msg.content);
      }
    }
    this.scrollToBottom();
  }
  /** Append a completed message (rendered as Markdown) to the list. */
  appendMessage(role, content) {
    var _a, _b;
    const el = this.messagesEl.createDiv({
      cls: `ai-harness-msg ai-harness-msg-${role}`
    });
    el.createDiv({ cls: "ai-harness-msg-role", text: role === "user" ? "You" : "AI" });
    const body = el.createDiv({ cls: "ai-harness-msg-body" });
    import_obsidian.MarkdownRenderer.render(
      this.app,
      content,
      body,
      (_b = (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path) != null ? _b : "/",
      this
    ).catch(() => body.setText(content));
    this.scrollToBottom();
  }
  scrollToBottom() {
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
  }
  setBusy(busy) {
    this.busy = busy;
    this.sendBtn.disabled = busy;
    this.input.disabled = false;
  }
  setStatus(ok, text) {
    this.statusDot.className = `ai-harness-dot ${ok ? "ai-harness-dot-ok" : "ai-harness-dot-err"}`;
    this.statusEl.setText(text);
  }
  async checkConnection() {
    this.setStatus(false, "Checking connection\u2026");
    const result = await this.plugin.checkConnection();
    this.setStatus(result.ok, result.message);
  }
  async newConversation() {
    if (this.busy)
      return;
    await this.plugin.clearHistory();
    this.messagesEl.empty();
    this.messagesEl.createDiv({
      cls: "ai-harness-empty",
      text: "New conversation started."
    });
  }
  async send() {
    var _a, _b;
    const prompt = this.input.value.trim();
    if (!prompt || this.busy)
      return;
    this.input.value = "";
    this.setBusy(true);
    this.appendMessage("user", prompt);
    const liveEl = this.messagesEl.createDiv({
      cls: "ai-harness-msg ai-harness-msg-assistant"
    });
    liveEl.createDiv({ cls: "ai-harness-msg-role", text: "AI" });
    const liveBody = liveEl.createDiv({ cls: "ai-harness-msg-body" });
    let acc = "";
    this.controller = new AbortController();
    this.setStatus(true, "Thinking\u2026");
    try {
      const answer = await this.plugin.askAI(prompt, this.controller.signal, {
        onToken: (delta) => {
          acc += delta;
          liveBody.setText(acc);
          this.scrollToBottom();
        },
        onToolCall: (name) => {
          this.setStatus(true, `Using tool: ${name}\u2026`);
        }
      });
      liveBody.empty();
      await import_obsidian.MarkdownRenderer.render(
        this.app,
        answer,
        liveBody,
        (_b = (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path) != null ? _b : "/",
        this
      );
      this.setStatus(true, "Ready");
    } catch (err) {
      const message = err.message;
      liveBody.empty();
      if (err.name === "AbortError") {
        liveBody.setText("Cancelled.");
        this.setStatus(true, "Cancelled");
      } else {
        liveBody.createEl("p", { cls: "ai-harness-error", text: `Error: ${message}` });
        this.setStatus(false, "Disconnected");
        this.checkConnection();
      }
    } finally {
      this.setBusy(false);
      this.controller = null;
    }
  }
};

// ndjson.ts
var NdjsonAccumulator = class {
  constructor() {
    this.buffer = "";
  }
  /**
   * Append a decoded chunk of text and return every complete JSON value that
   * can now be parsed. Incomplete trailing data stays buffered.
   */
  feed(text) {
    this.buffer += text;
    const out = [];
    let idx;
    while ((idx = this.buffer.indexOf("\n")) !== -1) {
      const line = this.buffer.slice(0, idx).trim();
      this.buffer = this.buffer.slice(idx + 1);
      if (!line)
        continue;
      try {
        out.push(JSON.parse(line));
      } catch (e) {
      }
    }
    return out;
  }
  /**
   * Best-effort parse of any remaining buffered line that never received a
   * trailing newline. Clears the buffer. Returns `[]` if nothing parseable.
   */
  flush() {
    const rest = this.buffer.trim();
    this.buffer = "";
    if (!rest)
      return [];
    try {
      return [JSON.parse(rest)];
    } catch (e) {
      return [];
    }
  }
};

// manifest.json
var manifest_default = {
  id: "ai-harness",
  name: "AI Harness",
  version: "0.3.0",
  minAppVersion: "1.0.0",
  description: "A persistent AI chat panel in Obsidian that talks to qwen3.8 via Ollama over an SSH tunnel.",
  author: "laurits",
  isDesktopOnly: true
};

// version.ts
var HARNESS_VERSION = manifest_default.version;

// main.ts
var DEFAULT_SETTINGS = {
  ollamaHost: "http://localhost:11434",
  model: "qwen3.8:27b",
  systemPrompt: "You are a helpful assistant.",
  timeoutMs: 6e4
};
var _AIHarnessPlugin = class _AIHarnessPlugin extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    /** Plugin version (kept in sync with `manifest.json`). */
    this.version = HARNESS_VERSION;
    /**
     * Conversation memory: the running list of user/assistant messages for the
     * current session. Tool-call messages are transient (per request) and are not
     * stored here. Cleared when the user starts a "New conversation".
     */
    this.history = [];
    /**
     * A tool the model can call. `run` receives the parsed arguments and returns
     * a string result that is fed back to the model.
     */
    this.tools = [
      {
        name: "get_current_note",
        description: "Get the title and full markdown content of the note currently open in Obsidian. Use this when the user refers to 'this note', 'the current note', or asks about content you don't already have.",
        parameters: { type: "object", properties: {}, required: [] },
        run: async () => {
          const file = this.app.workspace.getActiveFile();
          if (!file) {
            return "No note is currently open.";
          }
          const content = await this.app.vault.read(file);
          return `Title: ${file.name}
Path: ${file.path}

${content}`;
        }
      },
      {
        name: "edit_note",
        description: "Make a targeted edit to a note by replacing one exact block of text with new text. Safer than rewriting the whole note: only the matched region changes. 'old_text' must appear EXACTLY once in the note (match whitespace/indentation precisely). Use 'path' to target a specific note, or omit it to edit the currently open note. Set 'create_if_missing' to true to create the note with 'new_text' if it doesn't exist yet.",
        parameters: {
          type: "object",
          properties: {
            path: {
              type: "string",
              description: "Vault-relative note path (e.g. 'Signalbehandling/ADC.md'). Omit to use the active note."
            },
            old_text: {
              type: "string",
              description: "The exact existing text to replace. Must occur exactly once."
            },
            new_text: {
              type: "string",
              description: "The replacement text."
            },
            create_if_missing: {
              type: "boolean",
              description: "If the note doesn't exist, create it containing new_text. Default false."
            }
          },
          required: ["old_text", "new_text"]
        },
        run: async (args) => {
          var _a, _b, _c;
          const oldText = String((_a = args.old_text) != null ? _a : "");
          const newText = String((_b = args.new_text) != null ? _b : "");
          const createIfMissing = args.create_if_missing === true;
          const file = this.resolveNoteFile(args.path);
          if (!file) {
            if (createIfMissing) {
              return this.createNote(String((_c = args.path) != null ? _c : ""), newText);
            }
            return "Error: no target note found. Provide a valid 'path' or open a note.";
          }
          const content = await this.app.vault.read(file);
          const count = content.split(oldText).length - 1;
          if (count === 0) {
            return `Error: 'old_text' was not found in ${file.path}. Read the note first and copy the exact text.`;
          }
          if (count > 1) {
            return `Error: 'old_text' matched ${count} times in ${file.path}. Provide a longer, more unique snippet.`;
          }
          const updated = content.replace(oldText, () => newText);
          await this.app.vault.modify(file, updated);
          return `Edited ${file.path} (replaced 1 occurrence).`;
        }
      },
      {
        name: "write_note",
        description: "Create a new note, or fully overwrite an existing one, with the given markdown content. Use for creating new notes or replacing an entire note. For small changes prefer edit_note. Provide a vault-relative 'path' (e.g. 'Signalbehandling/New.md').",
        parameters: {
          type: "object",
          properties: {
            path: {
              type: "string",
              description: "Vault-relative note path, e.g. 'Signalbehandling/New.md'."
            },
            content: {
              type: "string",
              description: "The full markdown content to write."
            },
            overwrite: {
              type: "boolean",
              description: "If true, replace an existing note. If false (default), refuse to overwrite."
            }
          },
          required: ["path", "content"]
        },
        run: async (args) => {
          var _a, _b;
          const path = String((_a = args.path) != null ? _a : "").trim();
          const content = String((_b = args.content) != null ? _b : "");
          const overwrite = args.overwrite === true;
          if (!path)
            return "Error: 'path' is required.";
          if (!content)
            return "Error: 'content' is required.";
          const existing = this.app.vault.getAbstractFileByPath(path);
          if (existing) {
            if (!overwrite) {
              return `Note ${path} already exists. Set overwrite=true to replace it, or use edit_note for a targeted change.`;
            }
            if (!(existing instanceof import_obsidian2.TFile)) {
              return `Error: ${path} is not a note (it's a folder).`;
            }
            await this.app.vault.modify(existing, content);
            return `Overwrote ${path}.`;
          }
          return this.createNote(path, content);
        }
      }
    ];
  }
  async onload() {
    await this.loadAll();
    this.registerView(VIEW_TYPE_CHAT, (leaf) => new ChatView(leaf, this));
    this.addRibbonIcon("message-square", "AI Chat (toggle)", () => {
      this.toggleChatView();
    });
    this.addCommand({
      id: "toggle-ai-chat",
      name: "Toggle AI Chat",
      callback: () => this.toggleChatView()
    });
    this.addCommand({
      id: "open-ai-chat",
      name: "Open AI Chat",
      callback: () => this.openChatView()
    });
    this.addCommand({
      id: "close-ai-chat",
      name: "Close AI Chat",
      callback: () => this.closeChatView()
    });
    this.addSettingTab(new AIHarnessSettingTab(this.app, this));
  }
  onunload() {
  }
  /** True if any visible chat panel is currently open. */
  hasOpenChat() {
    return this.app.workspace.getLeavesOfType(VIEW_TYPE_CHAT).length > 0;
  }
  /** Open (or focus) the chat panel in the right sidebar. */
  async openChatView() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_CHAT)[0];
    if (existing) {
      workspace.revealLeaf(existing);
      return;
    }
    let leaf = workspace.getRightLeaf(true);
    if (!leaf) {
      leaf = workspace.getLeaf("split", "vertical");
    }
    await leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true });
  }
  /** Close (detach) any open chat panel. */
  closeChatView() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_CHAT);
  }
  /** Open the chat if it isn't open, otherwise close it. */
  async toggleChatView() {
    if (this.hasOpenChat()) {
      this.closeChatView();
    } else {
      await this.openChatView();
    }
  }
  /**
   * Load persisted data, migrating the legacy settings-only format into the
   * new `{ settings, history }` shape.
   */
  async loadAll() {
    const raw = await this.loadData();
    if (raw && typeof raw === "object" && "settings" in raw) {
      const data = raw;
      this.settings = Object.assign({}, DEFAULT_SETTINGS, data.settings);
      this.history = Array.isArray(data.history) ? data.history : [];
    } else {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, raw != null ? raw : {});
      this.history = [];
    }
  }
  /** Persist both settings and conversation history. */
  async saveAll() {
    const data = { settings: this.settings, history: this.history };
    await this.saveData(data);
  }
  /** Persist only the settings (used by the settings tab). */
  async saveSettings() {
    await this.saveAll();
  }
  /**
   * Resolve a note to edit. If `path` is given, look it up (must be an existing
   * note); otherwise fall back to the currently active file.
   */
  resolveNoteFile(path) {
    if (typeof path === "string" && path.trim()) {
      const f = this.app.vault.getAbstractFileByPath(path.trim());
      return f instanceof import_obsidian2.TFile ? f : null;
    }
    const active = this.app.workspace.getActiveFile();
    return active instanceof import_obsidian2.TFile ? active : null;
  }
  /**
   * Create a new note at a vault-relative path, creating parent folders as
   * needed. Guards against path traversal outside the vault.
   */
  async createNote(path, content) {
    const normalized = path.replace(/^\/+/, "");
    if (normalized.includes("..")) {
      return "Error: path must stay inside the vault (no '..').";
    }
    const parts = normalized.split("/").filter(Boolean);
    const fileName = parts.pop();
    if (!fileName)
      return "Error: invalid note path.";
    let folder = this.app.vault.getRoot();
    for (const dir of parts) {
      const next = this.app.vault.getAbstractFileByPath(
        `${folder.path === "/" ? "" : folder.path + "/"}${dir}`
      );
      if (next) {
        if (!next.children) {
          return `Error: '${dir}' is not a folder.`;
        }
        folder = next;
      } else {
        folder = await this.app.vault.createFolder(
          `${folder.path === "/" ? "" : folder.path + "/"}${dir}`
        );
      }
    }
    const targetPath = `${folder.path === "/" ? "" : folder.path + "/"}${fileName}`;
    const file = await this.app.vault.create(targetPath, content);
    return `Created ${file.path}.`;
  }
  /** Drop all conversation memory and persist the reset. */
  async clearHistory() {
    this.history = [];
    await this.saveAll();
  }
  /**
   * Check whether Ollama is reachable (e.g. the SSH tunnel is up). Pings the
   * lightweight `/api/version` endpoint with a short timeout.
   */
  async checkConnection() {
    const base = this.settings.ollamaHost.replace(/\/+$/, "");
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 3e3);
    try {
      const res = await fetch(`${base}/api/version`, { signal: controller.signal });
      if (res.ok) {
        const data = await res.json().catch(() => ({}));
        return { ok: true, message: data.version ? `Ollama ${data.version}` : "Connected" };
      }
      return { ok: false, message: `Ollama responded with ${res.status}` };
    } catch (err) {
      if (err.name === "AbortError") {
        return { ok: false, message: "Connection timed out (3s)" };
      }
      return { ok: false, message: "Could not reach Ollama \u2014 is the SSH tunnel running?" };
    } finally {
      clearTimeout(timer);
    }
  }
  /**
   * Send a prompt to Ollama (qwen3.8) over the local SSH-tunneled endpoint.
   *
   * - Streams the assistant's text back via `callbacks.onToken`.
   * - Supports tool calling: if the model requests a tool, we run it and feed
   *   the result back, looping until it returns a final text answer.
   * - Uses `this.history` for multi-turn conversation memory.
   * - Honors `signal` for cancellation.
   *
   * Returns the full assembled answer text.
   */
  async askAI(prompt, signal, callbacks = {}) {
    var _a, _b, _c, _d, _e;
    const base = this.settings.ollamaHost.replace(/\/+$/, "");
    const url = `${base}/api/chat`;
    const messages = [
      { role: "system", content: this.settings.systemPrompt },
      ...this.history,
      { role: "user", content: prompt }
    ];
    const ollamaTools = this.tools.map((t) => ({
      type: "function",
      function: {
        name: t.name,
        description: t.description,
        parameters: t.parameters
      }
    }));
    const MAX_TOOL_ROUNDS = 5;
    let finalAnswer = "";
    const timeoutMs = this.settings.timeoutMs;
    let timedOut = false;
    let timer;
    const timeoutController = new AbortController();
    const armTimeout = () => {
      if (timer)
        clearTimeout(timer);
      timer = setTimeout(() => {
        timedOut = true;
        timeoutController.abort();
      }, timeoutMs);
    };
    const onAbort = () => timeoutController.abort();
    signal.addEventListener("abort", onAbort, { once: true });
    armTimeout();
    try {
      for (let round = 0; round <= MAX_TOOL_ROUNDS; round++) {
        if (signal.aborted)
          throw new DOMException("Aborted", "AbortError");
        const body = {
          model: this.settings.model,
          stream: true,
          tools: ollamaTools,
          messages
        };
        let res;
        try {
          res = await fetch(url, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(body),
            signal: timeoutController.signal
          });
        } catch (err) {
          if (err.name === "AbortError") {
            if (timedOut) {
              throw new Error(
                `Request timed out (no response for ${timeoutMs}ms). Is the model still loading? You can raise the timeout in settings.`
              );
            }
            throw err;
          }
          throw new Error(
            `Could not reach Ollama at ${url}. Is the SSH tunnel running? (run ./start-tunnel.sh)`
          );
        }
        if (!res.ok) {
          const text = await res.text().catch(() => "");
          throw new Error(`Ollama responded with ${res.status}: ${text}`);
        }
        const reader = (_a = res.body) == null ? void 0 : _a.getReader();
        if (!reader)
          throw new Error("No response body to stream from.");
        const decoder = new TextDecoder();
        const accumulator = new NdjsonAccumulator();
        const stream = { content: "", toolCalls: void 0 };
        const handleChunk = (chunk) => {
          var _a2, _b2;
          const c = chunk;
          const msg = c == null ? void 0 : c.message;
          if (!msg)
            return;
          if (msg.content) {
            stream.content += msg.content;
            (_a2 = callbacks.onToken) == null ? void 0 : _a2.call(callbacks, msg.content);
          }
          if (Array.isArray(msg.tool_calls) && msg.tool_calls.length > 0) {
            stream.toolCalls = ((_b2 = stream.toolCalls) != null ? _b2 : []).concat(msg.tool_calls);
          }
        };
        while (true) {
          let readResult;
          try {
            readResult = await reader.read();
          } catch (err) {
            if (timedOut) {
              throw new Error(
                `Request timed out (no data for ${timeoutMs}ms). You can raise the timeout in settings.`
              );
            }
            throw err;
          }
          const { done, value } = readResult;
          if (done) {
            for (const chunk of accumulator.flush())
              handleChunk(chunk);
            break;
          }
          armTimeout();
          for (const chunk of accumulator.feed(decoder.decode(value, { stream: true }))) {
            handleChunk(chunk);
          }
        }
        const content = stream.content;
        const toolCalls = stream.toolCalls;
        if (toolCalls && toolCalls.length > 0) {
          messages.push({ role: "assistant", content, tool_calls: toolCalls });
          for (const call of toolCalls) {
            const fnName = (_b = call == null ? void 0 : call.function) == null ? void 0 : _b.name;
            const args = (_d = (_c = call == null ? void 0 : call.function) == null ? void 0 : _c.arguments) != null ? _d : {};
            (_e = callbacks.onToolCall) == null ? void 0 : _e.call(callbacks, fnName);
            const tool = this.tools.find((t) => t.name === fnName);
            let result;
            if (!tool) {
              result = `Error: unknown tool "${fnName}".`;
            } else {
              try {
                result = await tool.run(args);
              } catch (err) {
                result = `Error running tool "${fnName}": ${err.message}`;
              }
            }
            messages.push({ role: "tool", name: fnName, content: result });
          }
          continue;
        }
        finalAnswer = content;
        break;
      }
      if (!finalAnswer) {
        throw new Error("Stopped: too many tool-call rounds without a final answer.");
      }
      this.history.push({ role: "user", content: prompt });
      this.history.push({ role: "assistant", content: finalAnswer });
      const maxMessages = _AIHarnessPlugin.MAX_HISTORY_TURNS * 2;
      if (this.history.length > maxMessages) {
        this.history = this.history.slice(this.history.length - maxMessages);
      }
      return finalAnswer;
    } finally {
      if (timer)
        clearTimeout(timer);
      signal.removeEventListener("abort", onAbort);
    }
  }
};
/** Maximum number of user/assistant turns kept in memory. */
_AIHarnessPlugin.MAX_HISTORY_TURNS = 40;
var AIHarnessPlugin = _AIHarnessPlugin;
var AIHarnessSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: `AI Harness (v${this.plugin.version})` });
    new import_obsidian2.Setting(containerEl).setName("Ollama host").setDesc("Base URL of Ollama (behind your SSH tunnel).").addText(
      (text) => text.setPlaceholder("http://localhost:11434").setValue(this.plugin.settings.ollamaHost).onChange(async (value) => {
        this.plugin.settings.ollamaHost = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Model").setDesc("Ollama model name to use.").addText(
      (text) => text.setPlaceholder("qwen3.8:27b").setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("System prompt").setDesc("Optional system prompt prepended to every request.").addTextArea(
      (ta) => ta.setPlaceholder("You are a helpful assistant.").setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Request timeout").setDesc(
      "Abort a request if no data arrives for this long (seconds). Raise it if large models take a while to start responding."
    ).addSlider(
      (slider) => slider.setLimits(5, 300, 5).setValue(Math.round(this.plugin.settings.timeoutMs / 1e3)).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.timeoutMs = value * 1e3;
        await this.plugin.saveSettings();
      })
    );
  }
};
