/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD (see esbuild.config.mjs)
If you want to view the source, see main.ts in this folder.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AIHarnessPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  ollamaHost: "http://localhost:11434",
  model: "qwen3.8:27b",
  systemPrompt: "You are a helpful assistant."
};
var _AIHarnessPlugin = class _AIHarnessPlugin extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    /**
     * Conversation memory: the running list of user/assistant messages for the
     * current session. Tool-call messages are transient (per request) and are not
     * stored here. Cleared when the user hits "Clear" in the modal.
     */
    this.history = [];
    /**
     * A tool the model can call. `run` receives the parsed arguments and returns
     * a string result that is fed back to the model.
     */
    this.tools = [
      {
        name: "get_current_note",
        description: "Get the title and full markdown content of the note currently open in Obsidian. Use this when the user refers to 'this note', 'the current note', or asks about content you don't already have.",
        parameters: { type: "object", properties: {}, required: [] },
        run: async () => {
          const file = this.app.workspace.getActiveFile();
          if (!file) {
            return "No note is currently open.";
          }
          const content = await this.app.vault.read(file);
          return `Title: ${file.name}
Path: ${file.path}

${content}`;
        }
      },
      {
        name: "edit_note",
        description: "Make a targeted edit to a note by replacing one exact block of text with new text. Safer than rewriting the whole note: only the matched region changes. 'old_text' must appear EXACTLY once in the note (match whitespace/indentation precisely). Use 'path' to target a specific note, or omit it to edit the currently open note. Set 'create_if_missing' to true to create the note with 'new_text' if it doesn't exist yet.",
        parameters: {
          type: "object",
          properties: {
            path: {
              type: "string",
              description: "Vault-relative note path (e.g. 'Signalbehandling/ADC.md'). Omit to use the active note."
            },
            old_text: {
              type: "string",
              description: "The exact existing text to replace. Must occur exactly once."
            },
            new_text: {
              type: "string",
              description: "The replacement text."
            },
            create_if_missing: {
              type: "boolean",
              description: "If the note doesn't exist, create it containing new_text. Default false."
            }
          },
          required: ["old_text", "new_text"]
        },
        run: async (args) => {
          var _a, _b, _c;
          const oldText = String((_a = args.old_text) != null ? _a : "");
          const newText = String((_b = args.new_text) != null ? _b : "");
          const createIfMissing = args.create_if_missing === true;
          const file = this.resolveNoteFile(args.path);
          if (!file) {
            if (createIfMissing) {
              return this.createNote(String((_c = args.path) != null ? _c : ""), newText);
            }
            return "Error: no target note found. Provide a valid 'path' or open a note.";
          }
          const content = await this.app.vault.read(file);
          const count = content.split(oldText).length - 1;
          if (count === 0) {
            return `Error: 'old_text' was not found in ${file.path}. Read the note first and copy the exact text.`;
          }
          if (count > 1) {
            return `Error: 'old_text' matched ${count} times in ${file.path}. Provide a longer, more unique snippet.`;
          }
          const updated = content.replace(oldText, newText);
          await this.app.vault.modify(file, updated);
          return `Edited ${file.path} (replaced 1 occurrence).`;
        }
      },
      {
        name: "write_note",
        description: "Create a new note, or fully overwrite an existing one, with the given markdown content. Use for creating new notes or replacing an entire note. For small changes prefer edit_note. Provide a vault-relative 'path' (e.g. 'Signalbehandling/New.md').",
        parameters: {
          type: "object",
          properties: {
            path: {
              type: "string",
              description: "Vault-relative note path, e.g. 'Signalbehandling/New.md'."
            },
            content: {
              type: "string",
              description: "The full markdown content to write."
            },
            overwrite: {
              type: "boolean",
              description: "If true, replace an existing note. If false (default), refuse to overwrite."
            }
          },
          required: ["path", "content"]
        },
        run: async (args) => {
          var _a, _b;
          const path = String((_a = args.path) != null ? _a : "").trim();
          const content = String((_b = args.content) != null ? _b : "");
          const overwrite = args.overwrite === true;
          if (!path)
            return "Error: 'path' is required.";
          if (!content)
            return "Error: 'content' is required.";
          const existing = this.app.vault.getAbstractFileByPath(path);
          if (existing) {
            if (!overwrite) {
              return `Note ${path} already exists. Set overwrite=true to replace it, or use edit_note for a targeted change.`;
            }
            if (!(existing instanceof import_obsidian.TFile)) {
              return `Error: ${path} is not a note (it's a folder).`;
            }
            await this.app.vault.modify(existing, content);
            return `Overwrote ${path}.`;
          }
          return this.createNote(path, content);
        }
      }
    ];
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("message-square", "Ask AI", () => {
      new PromptModal(this.app, this).open();
    });
    this.addCommand({
      id: "ask-ai",
      name: "Ask AI",
      callback: () => new PromptModal(this.app, this).open()
    });
    this.addSettingTab(new AIHarnessSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Resolve a note to edit. If `path` is given, look it up (must be an existing
   * note); otherwise fall back to the currently active file.
   */
  resolveNoteFile(path) {
    if (typeof path === "string" && path.trim()) {
      const f = this.app.vault.getAbstractFileByPath(path.trim());
      return f instanceof import_obsidian.TFile ? f : null;
    }
    const active = this.app.workspace.getActiveFile();
    return active instanceof import_obsidian.TFile ? active : null;
  }
  /**
   * Create a new note at a vault-relative path, creating parent folders as
   * needed. Guards against path traversal outside the vault.
   */
  async createNote(path, content) {
    const normalized = path.replace(/^\/+/, "");
    if (normalized.includes("..")) {
      return "Error: path must stay inside the vault (no '..').";
    }
    const parts = normalized.split("/").filter(Boolean);
    const fileName = parts.pop();
    if (!fileName)
      return "Error: invalid note path.";
    let folder = this.app.vault.getRoot();
    for (const dir of parts) {
      const next = this.app.vault.getAbstractFileByPath(
        `${folder.path === "/" ? "" : folder.path + "/"}${dir}`
      );
      if (next) {
        if (!next.children) {
          return `Error: '${dir}' is not a folder.`;
        }
        folder = next;
      } else {
        folder = await this.app.vault.createFolder(
          `${folder.path === "/" ? "" : folder.path + "/"}${dir}`
        );
      }
    }
    const targetPath = `${folder.path === "/" ? "" : folder.path + "/"}${fileName}`;
    const file = await this.app.vault.create(targetPath, content);
    return `Created ${file.path}.`;
  }
  /** Drop all conversation memory. */
  clearHistory() {
    this.history = [];
  }
  /**
   * Send a prompt to Ollama (qwen3.8) over the local SSH-tunneled endpoint.
   *
   * - Streams the assistant's text back via `callbacks.onToken`.
   * - Supports tool calling: if the model requests a tool, we run it and feed
   *   the result back, looping until it returns a final text answer.
   * - Uses `this.history` for multi-turn conversation memory.
   * - Honors `signal` for cancellation.
   *
   * Returns the full assembled answer text.
   */
  async askAI(prompt, signal, callbacks = {}) {
    var _a, _b, _c, _d, _e, _f;
    const base = this.settings.ollamaHost.replace(/\/+$/, "");
    const url = `${base}/api/chat`;
    const messages = [
      { role: "system", content: this.settings.systemPrompt },
      ...this.history,
      { role: "user", content: prompt }
    ];
    const ollamaTools = this.tools.map((t) => ({
      type: "function",
      function: {
        name: t.name,
        description: t.description,
        parameters: t.parameters
      }
    }));
    const MAX_TOOL_ROUNDS = 5;
    let finalAnswer = "";
    for (let round = 0; round <= MAX_TOOL_ROUNDS; round++) {
      if (signal.aborted)
        throw new DOMException("Aborted", "AbortError");
      const body = {
        model: this.settings.model,
        stream: true,
        tools: ollamaTools,
        messages
      };
      let res;
      try {
        res = await fetch(url, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(body),
          signal
        });
      } catch (err) {
        if (err.name === "AbortError")
          throw err;
        throw new Error(
          `Could not reach Ollama at ${url}. Is the SSH tunnel running? (run ./start-tunnel.sh)`
        );
      }
      if (!res.ok) {
        const text = await res.text().catch(() => "");
        throw new Error(`Ollama responded with ${res.status}: ${text}`);
      }
      const reader = (_a = res.body) == null ? void 0 : _a.getReader();
      if (!reader)
        throw new Error("No response body to stream from.");
      const decoder = new TextDecoder();
      let buffer = "";
      let content = "";
      let toolCalls = void 0;
      while (true) {
        const { done, value } = await reader.read();
        if (done)
          break;
        buffer += decoder.decode(value, { stream: true });
        let idx;
        while ((idx = buffer.indexOf("\n")) !== -1) {
          const line = buffer.slice(0, idx).trim();
          buffer = buffer.slice(idx + 1);
          if (!line)
            continue;
          let chunk;
          try {
            chunk = JSON.parse(line);
          } catch (e) {
            continue;
          }
          const msg = chunk == null ? void 0 : chunk.message;
          if (msg == null ? void 0 : msg.content) {
            content += msg.content;
            (_b = callbacks.onToken) == null ? void 0 : _b.call(callbacks, msg.content);
          }
          if (Array.isArray(msg == null ? void 0 : msg.tool_calls) && msg.tool_calls.length > 0) {
            toolCalls = (toolCalls != null ? toolCalls : []).concat(msg.tool_calls);
          }
          if (chunk == null ? void 0 : chunk.done) {
          }
        }
      }
      if (toolCalls && toolCalls.length > 0) {
        messages.push({ role: "assistant", content, tool_calls: toolCalls });
        for (const call of toolCalls) {
          const fnName = (_c = call == null ? void 0 : call.function) == null ? void 0 : _c.name;
          const args = (_e = (_d = call == null ? void 0 : call.function) == null ? void 0 : _d.arguments) != null ? _e : {};
          (_f = callbacks.onToolCall) == null ? void 0 : _f.call(callbacks, fnName);
          const tool = this.tools.find((t) => t.name === fnName);
          let result;
          if (!tool) {
            result = `Error: unknown tool "${fnName}".`;
          } else {
            try {
              result = await tool.run(args);
            } catch (err) {
              result = `Error running tool "${fnName}": ${err.message}`;
            }
          }
          messages.push({ role: "tool", name: fnName, content: result });
        }
        continue;
      }
      finalAnswer = content;
      break;
    }
    if (!finalAnswer) {
      throw new Error("Stopped: too many tool-call rounds without a final answer.");
    }
    this.history.push({ role: "user", content: prompt });
    this.history.push({ role: "assistant", content: finalAnswer });
    const maxMessages = _AIHarnessPlugin.MAX_HISTORY_TURNS * 2;
    if (this.history.length > maxMessages) {
      this.history = this.history.slice(this.history.length - maxMessages);
    }
    return finalAnswer;
  }
};
/** Maximum number of user/assistant turns kept in memory. */
_AIHarnessPlugin.MAX_HISTORY_TURNS = 40;
var AIHarnessPlugin = _AIHarnessPlugin;
var PromptModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.controller = null;
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("ai-harness-modal");
    contentEl.createEl("h3", { text: "Ask AI" });
    this.input = contentEl.createEl("textarea", {
      cls: "ai-harness-input",
      placeholder: "Type your prompt\u2026  (Ctrl/\u2318 + Enter to send)"
    });
    const actions = contentEl.createDiv({ cls: "ai-harness-actions" });
    this.sendBtn = new import_obsidian.ButtonComponent(actions).setButtonText("Send").setCta().onClick(() => this.send());
    this.cancelBtn = new import_obsidian.ButtonComponent(actions).setButtonText("Cancel").setDisabled(true).onClick(() => {
      var _a;
      return (_a = this.controller) == null ? void 0 : _a.abort();
    });
    this.clearBtn = new import_obsidian.ButtonComponent(actions).setButtonText("Clear").onClick(() => this.clear());
    this.closeBtn = new import_obsidian.ButtonComponent(actions).setButtonText("Close").onClick(() => this.close());
    this.statusEl = contentEl.createDiv({ cls: "ai-harness-status" });
    this.output = contentEl.createDiv({ cls: "ai-harness-output" });
    this.input.addEventListener("keydown", (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
        e.preventDefault();
        this.send();
      }
    });
    this.input.focus();
  }
  setBusy(busy) {
    this.sendBtn.setDisabled(busy);
    this.cancelBtn.setDisabled(!busy);
    this.clearBtn.setDisabled(busy);
    this.closeBtn.setDisabled(busy);
  }
  clear() {
    this.plugin.clearHistory();
    this.output.empty();
    this.statusEl.empty();
  }
  async send() {
    var _a, _b;
    const prompt = this.input.value.trim();
    if (!prompt)
      return;
    this.controller = new AbortController();
    this.setBusy(true);
    this.output.empty();
    this.statusEl.setText("Thinking\u2026");
    const liveEl = this.output.createDiv({ cls: "ai-harness-answer" });
    let acc = "";
    try {
      const answer = await this.plugin.askAI(prompt, this.controller.signal, {
        onToken: (delta) => {
          acc += delta;
          liveEl.setText(acc);
          this.output.scrollTop = this.output.scrollHeight;
        },
        onToolCall: (name) => {
          this.statusEl.setText(`Using tool: ${name}\u2026`);
        }
      });
      this.output.empty();
      const rendered = this.output.createDiv({ cls: "ai-harness-answer" });
      await import_obsidian.MarkdownRenderer.render(
        this.app,
        answer,
        rendered,
        (_b = (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path) != null ? _b : "/",
        this
      );
      this.statusEl.empty();
    } catch (err) {
      const message = err.message;
      this.output.empty();
      if (err.name === "AbortError") {
        this.statusEl.setText("Cancelled.");
      } else {
        this.output.createEl("p", {
          cls: "ai-harness-error",
          text: `Error: ${message}`
        });
      }
    } finally {
      this.setBusy(false);
      this.controller = null;
    }
  }
  onClose() {
    var _a;
    (_a = this.controller) == null ? void 0 : _a.abort();
    this.contentEl.empty();
  }
};
var AIHarnessSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Ollama host").setDesc("Base URL of Ollama (behind your SSH tunnel).").addText(
      (text) => text.setPlaceholder("http://localhost:11434").setValue(this.plugin.settings.ollamaHost).onChange(async (value) => {
        this.plugin.settings.ollamaHost = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Model").setDesc("Ollama model name to use.").addText(
      (text) => text.setPlaceholder("qwen3.8:27b").setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("System prompt").setDesc("Optional system prompt prepended to every request.").addTextArea(
      (ta) => ta.setPlaceholder("You are a helpful assistant.").setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
